/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#26fedc",
        "primary-container": "#9d50bb",
        "secondary-container": "#573092",
        "surface-tint": "#edb1ff",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e2eb",
        "surface-container-lowest": "#0b0e14",
        "on-error": "#690005",
        "surface-variant": "#32353c",
        "on-tertiary-fixed": "#00201a",
        "surface-container": "#1d2026",
        "on-tertiary": "#00382f",
        "primary-fixed": "#f9d8ff",
        "on-secondary-fixed-variant": "#573092",
        "surface-dim": "#10131a",
        "on-secondary": "#40147a",
        "outline-variant": "#4e4350",
        "on-secondary-fixed": "#270057",
        "on-primary-container": "#fff3fd",
        "on-tertiary-fixed-variant": "#005144",
        "on-tertiary-container": "#dafff4",
        "surface-bright": "#363940",
        "on-secondary-container": "#c7a5ff",
        "outline": "#9a8c9b",
        "surface-container-low": "#191c22",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#6e208c",
        "on-background": "#e1e2eb",
        "error": "#ffb4ab",
        "tertiary-container": "#00806e",
        "secondary-fixed": "#ecdcff",
        "inverse-on-surface": "#2e3037",
        "tertiary-fixed-dim": "#00dfc1",
        "inverse-primary": "#883ca6",
        "on-primary-fixed": "#320046",
        "tertiary": "#00dfc1",
        "on-primary": "#520070",
        "surface-container-highest": "#32353c",
        "on-surface-variant": "#d1c2d2",
        "surface": "#10131a",
        "primary-fixed-dim": "#edb1ff",
        "background": "#10131a",
        "secondary": "#d6baff",
        "surface-container-high": "#272a31",
        "primary": "#edb1ff",
        "on-surface": "#e1e2eb",
        "secondary-fixed-dim": "#d6baff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Rajdhani", "Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "rajdhani": ["Rajdhani", "sans-serif"]
      }
    },
  },
  plugins: [],
}
